name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  app:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1e60f620b9541d7b38eae3e4d84e061b6c2f4f48 # v4.0.3
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: npm run check
